project: artefacts-demos/tron1-demo

version: 0.1.0

jobs:
  move_around:
    type: test
    runtime:
      framework: ros2:jazzy
      simulator: gazebo:harmonic
    package:
      docker:
        build:
          dockerfile: ./Dockerfile
    scenarios:
      defaults:
        output_dirs: ["test_report/latest/", "output"]
        pytest_file: test/art_test_move.py
      settings:
        - name: move
          params:
            move:
              - {name: "fw_1m+side_0.5m+dyaw_20", forward_m: 1.0, sideways_m: 0.5, dyaw_deg: 20, timeout_s: 20}
              - {name: "fw_5m+side_3m", forward_m: 5.0, sideways_m: 3.0, dyaw_deg: 0, timeout_s: 30}
        - name: move_face
          params:
            move_face:
              - {name: "dyaw_150+fw_5m", forward_m: 5.0, dyaw_deg: 150, hold: false, timeout_s: 35}
              - {name: "hold", forward_m: 3.5, dyaw_deg: 45, hold: true, hold_timeout_s: 3.5, timeout_s: 35}
              - {name: "timeout", forward_m: 0.0, dyaw_deg: 170, hold: false, timeout_s: 0.2}
  policy_test:
    type: test
    runtime:
      framework: ros2:jazzy
      simulator: gazebo:harmonic
    package:
      docker:
        build:
          dockerfile: ./Dockerfile
    scenarios:
      defaults:
        output_dirs: ["test_report/latest/", "output"]
        pytest_file: test/art_test_move.py
      settings:
        - name: move_face_with_different_policies
          params:
            rl_type: ["isaacgym", "isaaclab"]
            move_face:
              - {name: "dyaw_150+fw_5m", forward_m: 5.0, dyaw_deg: 150, hold: false, timeout_s: 35}
  policy_drift:
    type: test
    runtime:
      framework: ros2:jazzy
      simulator: gazebo:harmonic
    package:
      docker:
        build:
          dockerfile: ./Dockerfile
    scenarios:
      defaults:
        output_dirs: ["test_report/latest/", "output"]
        metrics: "output/metrics.json"
        pytest_file: test/art_test_drift.py
      settings:
        - name: idle_drift_compare_policies
          params:
            rl_type: ["isaacgym", "isaaclab"]
            durations_s: [10, 60]
